### ISSUE TITLE
Error for gene tree processing

### ISSUE THREAD

**Issue by zbyxinalice03** [kfuku52/RADTE#5]
Hi everyone:
       I try to run the RADTE program using my dataset. I replaced "_"  into "." in gene id, and modified species name into "genus_speicies". Then I executed Notung-2.9.1.5 to produce the rooted gene tree, with "--resolve" model used to avoid the polytomies.
My issue is that there is an error after "calibration node removed" when I ran RADTE, showing that "All attempts for divergence time estimation were failed. Exiting":

![error1](https://user-images.githubusercontent.com/78631091/178887341-15dc80f7-56ab-48ea-bda4-84cb0f67656f.png)
I can't figure out the reason for this error，have anyone met this error before?

**Comment by kfuku52** [comment]
Bifurcation should be done before running NOTUNG, and the task command of NOTUNG should be `--reconcile` rather than `--resolve` to make it compatible with RADTE. Could you try that?

**Comment by zbyxinalice03** [comment]
I will try to perform bifurcation. Is there any program you recommand to do this?

**Comment by kfuku52** [comment]
I used to use ape's `multi2di`.

**Comment by zbyxinalice03** [comment]
OK, I'll try it. Thank you very much.

**Comment by zbyxinalice03** [comment]
Hi:
My colleague recently found that there is an spelling error in your "README.md" file.  In the part of "Example 1: RADTE after NOTUNG",  "--chronos_model=difscrete" should be "--chronos_model=discrete". When my colleague modified this parameter, the program could be executed. We will try to perform the program using our own data after.

**Comment by kfuku52** [comment]
Thank you for reporting it. I will correct the typo.

**Comment by kfuku52** [comment]
Test coverage added in v0.2.4: The test suite now includes validation for zero branch length handling and gene tree processing edge cases (test-input-validation.R, test-edge-cases.R). A bug fix for `close(f)` in `read_notung_parsable` was also applied.
